version: '3'

services:
 web:
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app

  postgresdb:
   image: postgres
   ports:
   - 5432:5432
   enviroment:
   - POSTGRES_ROOT_PASSWORD=12345678
   volumes:
   - postgres: /var/lib/postgres
   - postgres_config: /etc/postgres

volumes:
 postgres:
 postgres_config: